module.exports = [{"id":1,"fkSenderId":2,"message":"Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","file":""},
{"id":2,"fkSenderId":9,"message":"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","file":"nulla.ppt"},
{"id":3,"fkSenderId":7,"message":"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","file":""},
{"id":4,"fkSenderId":10,"message":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","file":""},
{"id":5,"fkSenderId":3,"message":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","file":""},
{"id":6,"fkSenderId":10,"message":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","file":"egetTempus.xls"},
{"id":7,"fkSenderId":1,"message":"Quisque ut erat.","file":""},
{"id":8,"fkSenderId":1,"message":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","file":"euSapienCursus.mov"},
{"id":9,"fkSenderId":2,"message":"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.","file":""},
{"id":10,"fkSenderId":5,"message":"Nam dui.","file":""},
{"id":11,"fkSenderId":5,"message":"Proin interdum mauris non ligula pellentesque ultrices.","file":""},
{"id":12,"fkSenderId":8,"message":"Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.","file":""},
{"id":13,"fkSenderId":6,"message":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.","file":"libero.mp3"},
{"id":14,"fkSenderId":4,"message":"Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.","file":"nullaMollis.xls"},
{"id":15,"fkSenderId":2,"message":"Vivamus tortor. Duis mattis egestas metus.","file":"mattis.png"},
{"id":16,"fkSenderId":3,"message":"In eleifend quam a odio. In hac habitasse platea dictumst.","file":""},
{"id":17,"fkSenderId":3,"message":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","file":"fusceCongue.tiff"},
{"id":18,"fkSenderId":2,"message":"Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","file":"convallisTortorRisus.ppt"},
{"id":19,"fkSenderId":6,"message":"Vestibulum sed magna at nunc commodo placerat.","file":""},
{"id":20,"fkSenderId":1,"message":"Mauris ullamcorper purus sit amet nulla.","file":"rhoncusSed.ppt"},
{"id":21,"fkSenderId":5,"message":"Vestibulum ac est lacinia nisi venenatis tristique.","file":"sit.ppt"},
{"id":22,"fkSenderId":10,"message":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.","file":"aliquetMassa.tiff"},
{"id":23,"fkSenderId":3,"message":"Praesent blandit.","file":"plateaDictumst.ppt"},
{"id":24,"fkSenderId":9,"message":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","file":""},
{"id":25,"fkSenderId":1,"message":"Pellentesque at nulla.","file":"euNibh.avi"},
{"id":26,"fkSenderId":1,"message":"Ut tellus. Nulla ut erat id mauris vulputate elementum.","file":"dolorVel.xls"},
{"id":27,"fkSenderId":4,"message":"Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","file":"libero.mp3"},
{"id":28,"fkSenderId":2,"message":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","file":""},
{"id":29,"fkSenderId":3,"message":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","file":"nulla.mp3"},
{"id":30,"fkSenderId":3,"message":"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","file":""},
{"id":31,"fkSenderId":6,"message":"Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.","file":"ut.mov"},
{"id":32,"fkSenderId":10,"message":"Nulla facilisi.","file":""},
{"id":33,"fkSenderId":3,"message":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","file":"mattisPulvinar.ppt"},
{"id":34,"fkSenderId":2,"message":"Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.","file":""},
{"id":35,"fkSenderId":9,"message":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla.","file":"massaId.mp3"},
{"id":36,"fkSenderId":1,"message":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.","file":""},
{"id":37,"fkSenderId":5,"message":"Morbi ut odio.","file":"rhoncus.pdf"},
{"id":38,"fkSenderId":4,"message":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.","file":""},
{"id":39,"fkSenderId":4,"message":"Nullam sit amet turpis elementum ligula vehicula consequat.","file":"plateaDictumst.mp3"},
{"id":40,"fkSenderId":9,"message":"Nam tristique tortor eu pede.","file":"ipsum.xls"},
{"id":41,"fkSenderId":1,"message":"Duis at velit eu est congue elementum. In hac habitasse platea dictumst.","file":""},
{"id":42,"fkSenderId":3,"message":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","file":""},
{"id":43,"fkSenderId":9,"message":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","file":"praesent.mp3"},
{"id":44,"fkSenderId":7,"message":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","file":"elitProin.mp3"},
{"id":45,"fkSenderId":5,"message":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","file":"semSedSagittis.ppt"},
{"id":46,"fkSenderId":4,"message":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","file":""},
{"id":47,"fkSenderId":5,"message":"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","file":"vestibulumVelitId.pdf"},
{"id":48,"fkSenderId":1,"message":"Aenean sit amet justo. Morbi ut odio.","file":""},
{"id":49,"fkSenderId":2,"message":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","file":""},
{"id":50,"fkSenderId":10,"message":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","file":""}]