module.exports = [
  {
    id: 1,
    login: 'popovmaksim7415@gmail.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Maksim',
    lastName: 'Popov',
    tagName: 'maksim228',
    fullName: 'Maksim Popov',
    status: 'Available',
    verificationCode: '12345',
  },
  {
    id: 2,
    login: 'pwoolam1@nhs.uk',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Petronia',
    lastName: 'Woolam',
    tagName: 'pwoolam1',
    fullName: 'Petronia Woolam',
    status: 'Available',
  },
  {
    id: 3,
    login: 'dreveland2@discuz.net',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Demetra',
    lastName: '',
    tagName: 'dreveland2',
    fullName: 'Demetra',
    status: 'Not Available',
  },
  {
    id: 4,
    login: 'lgodfroy3@google.de',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Lyman',
    lastName: 'Godfroy',
    tagName: '',
    fullName: 'Lyman Godfroy',
    status: 'Blocked',
  },
  {
    id: 5,
    login: 'wvelasquez4@narod.ru',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Wilden',
    lastName: 'Velasquez',
    tagName: '',
    fullName: 'Wilden Velasquez',
    status: 'Available',
  },
  {
    id: 6,
    login: 'mgager5@about.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Michal',
    lastName: 'Gager',
    tagName: '',
    fullName: 'Michal Gager',
    status: 'Available',
  },
  {
    id: 7,
    login: 'mtither6@rambler.ru',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Mauricio',
    lastName: '',
    tagName: 'mtither6',
    fullName: 'Mauricio',
    status: 'Available',
  },
  {
    id: 8,
    login: 'aspavon7@oakley.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Aloisia',
    lastName: 'Spavon',
    tagName: '',
    fullName: 'Aloisia Spavon',
    status: 'Available',
  },
  {
    id: 9,
    login: 'lbalden8@washingtonpost.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Luce',
    lastName: 'Balden',
    tagName: '',
    fullName: 'Luce Balden',
    status: 'Blocked',
  },
  {
    id: 10,
    login: 'csandeford9@archive.org',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Cris',
    lastName: '',
    tagName: 'csandeford9',
    fullName: 'Cris',
    status: 'Available',
  },
  {
    id: 11,
    login: 'vit91112@gmail.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'vit9',
    lastName: '',
    tagName: 'vit9',
    fullName: 'vit9',
    status: 'Available',
    verificationCode: '12345',
  },
  {
    id: 12,
    login: 'kir221dol@gmail.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Kirill',
    lastName: 'Dolhopolov',
    tagName: 'x0r3k',
    fullName: 'Kirill Dolhopolov',
    status: 'Available',
    verificationCode: '12345',
  },
  {
    id: 13,
    login: 'userForTestUpdateProfile@mail.com',
    socketId: '23423423dfcxv',
    activityStatus: 'offline',
    firstName: 'Update',
    lastName: 'Profile',
    tagName: 'Upfate',
    fullName: 'Update Profile',
    status: 'Available',
    verificationCode: '12345',
  },
];
